services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Framework\Database\CompatibilityChecker\Bridge\DatabaseCheckerBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Database\CompatibilityChecker\Bridge\DatabaseCheckerBridge
    public: true
    arguments:
      - '@oxid_esales.framework.database.compatibility_checker.mysql_database_checker'

  oxid_esales.framework.database.compatibility_checker.mysql_database_checker:
    class: OxidEsales\EshopCommunity\Internal\Framework\Database\CompatibilityChecker\MysqlDatabaseChecker
    arguments:
      - '@oxid_esales.framework.database.compatibility_checker.mysql_version_dao'

  oxid_esales.framework.database.compatibility_checker.mysql_version_dao:
    class: OxidEsales\EshopCommunity\Internal\Framework\Database\CompatibilityChecker\MysqlVersionDao